# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c5160125712f0cc918895f4fe41940bc02ac979f0c7054d3a28da79e208861311f66e866c5fc69227e63325c0a356f0e1dcd8d98ef096ec815acc8a7639d592

test:
  secret_key_base: c3ed8380fcd868877bcf519259a76e1a57b052d2e55dc86edc9067f4696a381c6e8bab9164cc33abe732388a4fce3327571430dd745585ff6e68f6e1c9697333

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
